### ISSUE TITLE
Lack of data folder

### ISSUE THREAD

**Issue by alan-shangguan** [hololee/coarse-to-fine-segmentation-labelling#1]
Hi, Can you provide the data folder containing from data.DataUtils import SegDataset, InitializeData and 
from data.Transforms import ToTensor, Normalize, please?

**Comment by hololee** [comment]
HI @yuanyuangoo.
I added `data/` contained that scripts on main branch ([commit here](https://github.com/hololee/coarse-to-fine-segmentation-labelling/commit/0c8cfbba8c0098aa8ed09dd36d3477fb78910e21)).
Just extract from prev project,  So some little correction can be needed. (perhaps, I didn't checked scripts sorry.)

If some problem occured, remain here please. 

Thanks.

**Comment by alan-shangguan** [comment]
Thanks, is there any way I can have the Bean-field dataset you were using in this project?

**Comment by hololee** [comment]
I'm sorry, but `bean-field dataset` is private dataset for some project. so can't be shared. 🥲
(You can check sample input image form [here](https://github.com/hololee/coarse-to-fine-segmentation-labelling/blob/main/output/bean_leaf_solid/Main_combine/plot/a1.png).)

**Comment by hololee** [comment]
If you have more questions make another issue please!
